apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy-backend.fullname" . }}-kubeconfig
  labels:
{{ include "deploy-backend.labels" . | indent 4 }}
type: Opaque
stringData:
  config.yaml:
    {{- toYaml .Values.app.k8s.kubeconfigFileData | nindent 4 }}