apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy-backend.fullname" . }}-deployments
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}
