apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy-backend.fullname" . }}
  labels:
{{ include "deploy-backend.labels" . | indent 4 }}
type: Opaque
data:
  ACCESS_TOKEN: {{ .Values.app.acccessToken | b64enc | quote }}
  DEPLOYMENTS_DIR: {{ .Values.app.deploymentsDir | b64enc | quote }}
  HELM_REGISTRY_URL: {{ .Values.app.helm.registryUrl | b64enc | quote }}
  HELM_REGISTRY_USERNAME: {{ .Values.app.helm.username | b64enc | quote }}
  HELM_REGISTRY_USERNAME_PASSWORD: {{ .Values.app.helm.usernamePassword | b64enc | quote }}
  KUBERNETES_NAMESPACE: {{ .Values.app.k8s.namespace | b64enc | quote }}
  CELERY_BROKER: {{ .Values.app.celeryBroker | b64enc | quote }}
  BACKEND_BASE_URL: {{ .Values.app.backendBaseUrl | b64enc | quote }}
  BACKEND_ACCESS_TOKEN: {{ .Values.app.backendAccessToken | b64enc | quote }}