{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-redirect-scheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend.fullname" . }}-http
  annotations:
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host.name }}`)
      kind: Rule
      services:
        - kind: Service
          name: {{ include "backend.fullname" . }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: {{ .Release.Name }}-redirect-scheme
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cors-header
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowMethods:
      - "*"
    accessControlAllowHeaders:
      - "*"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend.fullname" . }}-https
  annotations:
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host.name }}`) && PathPrefix(`{{ .Values.ingress.host.path }}`)
      middlewares:
        - name: {{ .Release.Name }}-cors-header
      services:
        - kind: Service
          name: {{ include "backend.fullname" $ }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.service.port }}
          scheme: http
  {{- if .Values.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
    domains:
      - main: {{ .Values.ingress.host.name }}
  {{- end }}
{{- end }}
