apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
{{ include "backend.labels" . | indent 4 }}
type: Opaque
data:
  MONGO_USER: {{ .Values.app.mongo.user | b64enc | quote }}
  MONGO_PASSWORD: {{ .Values.app.mongo.password | b64enc | quote }}
  MONGO_HOST: {{ .Values.app.mongo.host | b64enc | quote }}
  MONGO_PORT: {{ .Values.app.mongo.port | b64enc | quote }}
  MONGO_DB_NAME: {{ .Values.app.mongo.dbName | b64enc | quote }}
  MONGO_AUTH_DB_NAME: {{ .Values.app.mongo.authDbName | b64enc | quote }}
  AUTH_BACKEND_BASE_URL: {{ .Values.app.authBackendBaseUrl | b64enc | quote }}
  DEPLOY_BACKEND_BASE_URL: {{ .Values.app.deployBackendBaseUrl | b64enc | quote }}
  DEPLOY_BACKEND_TOKEN: {{ .Values.app.deployBackendToken | b64enc | quote }}
  ACCESS_TOKEN: {{ .Values.app.acccessToken | b64enc | quote }}