app:
    mongo:
        user: ENC[AES256_GCM,data:PiEW1xMSIA==,iv:jPpX4uB8AC4YHDoYiPJNtB+dKOnT97VgF+tV35MLaGw=,tag:AnGd4PKYjEaiGAhH0Tevqg==,type:str]
        password: ENC[AES256_GCM,data:lFViNda/jbdcUN4nmLoXuFdRP3c=,iv:0gXuLgobEsmIl1DdzdqbiGIiWurmhGNGxSsCn7CalpY=,tag:uqw8DDFw7V08DYlbyvEPqA==,type:str]
        host: ENC[AES256_GCM,data:pWz7yM/xBECMJge+3+il,iv:V2Rog42jAwcQw+ScDFilzNFJHlQyG9ugEg6QLXkjRY4=,tag:IyOvObWAjaPPJCuos1IbtA==,type:str]
        dbName: ENC[AES256_GCM,data:g4QWd9luFg==,iv:1NRqs/IXSarUlmdIQSAdnUc6lDPt5hwcVduubqBMUrU=,tag:M5xMS8boFsk2g88Y6Ei6Ig==,type:str]
        authDbName: ENC[AES256_GCM,data:CLGyXV9Vhg==,iv:HTIiI4TfRv7BKKsqD2smXfI4Haa8FpPGl5pN/ZzlIls=,tag:uxZsa1y0FrJIMu8fRCDprQ==,type:str]
    authBackendBaseUrl: ENC[AES256_GCM,data:gDFklLt0pG05TE+3bwS+lNdH+3e1T6O7,iv:ygeRaM4rYFZeogfYqx5c0LX4e/NOaS8U2LyDC2ydYuE=,tag:KLlsjkUS/X+FlItA0Ac8nw==,type:str]
    deployBackendBaseUrl: ENC[AES256_GCM,data:6d2nuZi4BZjvhAfV/ae6L68eqkb97mzjFfQ=,iv:/LgAXo91bvhFIMjWOLJMdVH2jagYbKb3GWs7d2xaVjw=,tag:lrXC/Au8Wx2SdoyjM2vLxA==,type:str]
    deployBackendToken: ENC[AES256_GCM,data:nNb968/ktLe3H70JcIfYz2CEIN8=,iv:QV1VIazBdzh/Mo69343D72fakYiWnAZQeNL286eJDpI=,tag:6T/h6pTHxg3HCbBrwsZehA==,type:str]
    acccessToken: ENC[AES256_GCM,data:ZHTMw4FSLhWBNxvNW7Bd6Yk6Qpo=,iv:dH3r4eGxU2IHnLhqvPul9tgzk7sJjQQvj5ljTZLs9sg=,tag:GebftTSHs/s/G1MdXSfthQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-30T22:34:21Z"
    mac: ENC[AES256_GCM,data:+t2yClWrO6yuBeGht2IVoXzESqEWiCtHjjt7ZMbgG98j+ogXqfDGujdqLEG0JxF4YVOfzNTR1iu1XICMcxgMGAWXc78DfXYcGJdsod05RGmDsDj6E+i9LdPjhHQhja1XZCaUTvvvlqhr6YaobRX7UNvDwshUrf5YZg2LpeUPXz4=,iv:ZZwfDHA1zmAQo6df6svaCFW7wyIGhEBOHm0saEYyn2c=,tag:gNBJy8oY28t8ZoX05FOJVA==,type:str]
    pgp:
        - created_at: "2024-11-30T22:32:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9Onm9z5ejsrAQv7B4i3QNvVoFQCMjm/9v9CYQ7DWhcd0Ezt6Z5p/wwIG1GM
            WmBHGpSshLBiD0wHZIwNzAUNI69I40Oqv+w+6TIZbZvm02tdfqNhmt8hzfr2HV55
            UVepmK5CMaX0FPSgNkNHbh+rEiFCQ7xWBp3JzDDQ5O4YJnX/9A1j4e5sDUUkcFdY
            2jRJBmFqXwDkh/nFErp8Rya4+h77yJe+fVXExJcxSrlTB1RCg4oC9uF3WICqdd5b
            jB6j8y24JGpFRRS0AwkWULU5Rspoq002o7dXWGFnvYJWnwEBlswUHSrgQW7bngFt
            KTxGwb+tJOVTc5Q53zKd279syKmz2CP4FeT2pgVoY1zuL0hyFOzOIAjZXfg1w55G
            W/Ob8PZZVUOG6I/H/FjX3vN7yU46wuemLMj9pCYwj9LlWWBtAfDMUWaE43sxuQdq
            zd+RGkLKEphM97LHBrlQLj8OrJS3M5dRYmzd4kUP8p5fjUSmwJS99TAFE+fnNvoM
            FdLnpeD8jbNYgpRwqqDs0l4B2Dr/7I/ZToJdtM3qr3XFDrtDBcWrZnVlXvaKl4kY
            z7jZBbOX0zCc8u5UD8NJAmTDWnk3m/b2+vSRMDNJM5fQ+23wHdssPLms6Wj6bhoy
            ujKwcu8My+0oAjoXzhLW
            =V2jt
            -----END PGP MESSAGE-----
          fp: 8141CA94C017FEF615C0695F48890177955D87AF
    unencrypted_suffix: _unencrypted
    version: 3.9.0
