auth:
    username: ENC[AES256_GCM,data:7qPzTohk,iv:pP1kWG/vNQnjuKjcH2ovfT5CooQNerdg7gmc6o6PfMM=,tag:UYO8oIYXDbVajoF8/BnQ5g==,type:str]
    password: ENC[AES256_GCM,data:mGI6kDns0BGxFOB81SX8HlX48ls=,iv:Hd/9qsnYqvTgWnFnXN6OcBD2zdhoHzzXqQ31ewe23ME=,tag:4cmAvaCaJAOWwRhZVHaI5g==,type:str]
    erlangCookie: ENC[AES256_GCM,data:6dSlYucAYEa4PO8SQ32HXezNEy8=,iv:ILkGzSAeAwTVVvE4ySMUqaLIYT67ZoFUbTbSX8LDVds=,tag:6xxxTvlivRFRvwnVDYec0g==,type:str]
ldap:
    authorisationEnabled: ENC[AES256_GCM,data:ojNDRQ==,iv:T+Nu+QTe55Dnu7Hj7yxVSyicwDYJfwNnhsC/S6gu8+Y=,tag:JussoSbBOHR+KUbeJI2TOQ==,type:bool]
extraConfiguration: ENC[AES256_GCM,data:zK0/FER4un84zrvf0qTeaZAT2C/NdWwMB/WnZpOy4MXW/Ma+ZOfTOiUrbMnb0Atl2cFIV6UhAuwnY5pIEX5aVBQmrtT9DD33ybm+ytiASWm/DivJ3XAUFle3s/50uvIctQqM/7VIJ3KTU1MoOkzZbH6Rsd3vFQ==,iv:OpcwH2a6XYMF6yhov83qArDYoHuMZLq3jgIXgUQTfBM=,tag:Si4MsmtSu1j6Z/fO2y4chw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-01T09:56:58Z"
    mac: ENC[AES256_GCM,data:+RTE0e+XDhv0NKLLQ8Lmy6c5gPvegmUX+cGOKqFasepIJBipu8F30GaIb78e8KWE4k/nyNSSPt7Gq+YukvkwBDGRwGN8pfa1RbD67/lBjyNuH35wGCU3igx3/loFY3Ge9MU++MUS9bcvwKZ3vgYmH4rUKQSl/C5gFIroCNYvW2Q=,iv:5fYDa4j9wy3rhT3O1gUgBQH/Jx6EIanoeuA2PbWFXYQ=,tag:HCGOfPHIstAzkK63jVd/dA==,type:str]
    pgp:
        - created_at: "2024-12-01T09:56:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9Onm9z5ejsrAQwAshTufoo/AN8hmanMUZbKyMRgdRlE9UdRikCRmfb03jA0
            C7fAAeaEcRJCzRBSV0nHMmszHQq+5ys0+sz1zNu9ug/8JepcvG13s8e0ptCDSihB
            q0Qr1VJr4Ltsv9yG5HnOC48XLZ0GDeYxmoQ0PGZb4flr0MMcDVtoAyInJzGDArZe
            83exZ2wDYIq3JXCWffw6CS+b4nPPbkLxss0b2apfnxz5fMG8HvxY2WMNcoG+u0ND
            fhTaQ3kP5oFXYoygmoU0pzKfKgXUUsvRC3jW7mXYBdbStBHMW0qevc1a9i+9NUfC
            5mtFHcABy0v4GTVpbEgbYOnXLkpXQ124MG6CqI4oxOdkgvTPOmkrf9C6Ghmzbqs4
            HI0uB/X/sx3qrz+3lp/kVM7KVZkvN3B31dtcuJmOmWDlpb97TdCwTMuF6UHQ3kDb
            y1EHlr4oZB5yoxMsPiwF4uWaPem+yII90hXP4v7WlflxqN3AKx6WZR/4BPCyij8h
            G2FaYdbCI8VY7NznsZaq0l4BWG6qRBJq6j2lN6Zf5SDnPMeJo1pITXxkfY2oaC9R
            uXAE2nqdQOwxrKVHKnWsGdWOFMpxB/7fyuC76Q3B/PXdvFk/1+ll/SDJqpzsVuIq
            CvVmxcl3eQN5L5hVLka/
            =oV2d
            -----END PGP MESSAGE-----
          fp: 8141CA94C017FEF615C0695F48890177955D87AF
    unencrypted_suffix: _unencrypted
    version: 3.9.0
