apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-backend.fullname" . }}
  labels:
{{ include "auth-backend.labels" . | indent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql+asyncpg://%s:%s@%s/%s" .Values.app.database.user .Values.app.database.password .Values.app.database.host .Values.app.database.dbName | b64enc | quote }}
  SECRET_KEY: {{ .Values.app.secretKey | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.app.adminEmail | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.app.adminPassword | b64enc | quote }}