services:

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - "5433:5432"

  auth_backend:
    image: auth-dev
    build:
      context: auth_backend
      target: production
    ports:
      - 8003:8000
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/auth"
      SECRET_KEY: "your-secret-key"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "securepassword"

  frontend:
    image: frontend-dev
    depends_on:
      - auth_backend
    build:
      context: frontend
      target: production
    ports:
      - 8001:80
    environment:
      REACT_APP_AUTH_SERVICE_BASE_URL: http://localhost:8003
      REACT_APP_APPLICATIONS_SERVICE_BASE_URL: http://localhost:8002

  broker:
    image: rabbitmq:4-alpine
    volumes:
      - .rabbitmq:/var/lib/rabbitmq/mnesia/
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_VHOST=rabbit
      - RABBITMQ_DEFAULT_PASS=verysecurerabbit

  deploy_backend:
    image: deploy_backend
    build:
      context: deploy_backend
      target: production
    depends_on:
      - broker
    ports:
      - 8004:8000
    environment:
      ACCESS_TOKEN: oe6EiSh2ooth9boh8OoSheihie9soo3o
      DEPLOYMENTS_DIR: "/deployments"
      HELM_REGISTRY_URL: "https://helm.elastic.co"
      HELM_REGISTRY_USERNAME: "test_user"
      HELM_REGISTRY_USERNAME_PASSWORD: "test_user_pass"
      KUBERNETES_NAMESPACE: "test-ns"
      CELERY_BROKER: "amqp://rabbit:verysecurerabbit@broker:5672/rabbit"
      BACKEND_BASE_URL: http://master_work-backend-1:8000
      BACKEND_ACCESS_TOKEN: "tttttoken"
    volumes:
      - .deployments:/deployments

  deploy_backend_worker:
    image: deploy_backend_worker
    build:
      context: deploy_backend
      target: production
    depends_on:
      - broker
    environment:
      ACCESS_TOKEN: oe6EiSh2ooth9boh8OoSheihie9soo3o
      DEPLOYMENTS_DIR: "/deployments"
      HELM_REGISTRY_URL: "https://helm.elastic.co"
      HELM_REGISTRY_USERNAME: "test_user"
      HELM_REGISTRY_USERNAME_PASSWORD: "test_user_pass"
      KUBERNETES_NAMESPACE: "test-ns"
      CELERY_BROKER: "amqp://rabbit:verysecurerabbit@broker:5672/rabbit"
      BACKEND_BASE_URL: http://master_work-backend-1:8000
      BACKEND_ACCESS_TOKEN: "HahgiC8ar2aepaereneef3Yiey0NahCh"
    volumes:
      - .deployments:/deployments
    command: /.venv/bin/python -m celery -A celery_app.app worker -E -Q deployments

  mongodb:
    image: mongo:8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend-pass
    volumes:
      - .mongo:/data/db

  backend:
    image: backend-dev
    depends_on:
      - mongodb
      - deploy_backend
    build:
      context: backend
      target: production
    ports:
      - 8002:8000
    environment:
      MONGO_USER: backend
      MONGO_PASSWORD: backend-pass
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: backend
      MONGO_AUTH_DB_NAME: admin
      AUTH_BACKEND_BASE_URL: http://master_work-auth_backend-1:8000
      DEPLOY_BACKEND_BASE_URL: http://master_work-deploy_backend-1:8000
      DEPLOY_BACKEND_TOKEN: oe6EiSh2ooth9boh8OoSheihie9soo3o
      ACCESS_TOKEN: HahgiC8ar2aepaereneef3Yiey0NahCh

  mongosh:
    image: rtsp/mongosh
    depends_on:
      - mongodb

  greeting:
    image: alpine
    depends_on:
      - frontend
      - backend
      - mongodb
      - deploy_backend
    command:
      - sh
      - -c
      - |
        sleep 7;
        echo "----------------------------------------------";
        echo "To access the frontend follow the link: http://localhost:8001";
        echo "----------------------------------------------";
        echo "----------------------------------------------";
        echo "To access the backend docs follow the link: http://localhost:8002/docs";
        echo "----------------------------------------------";
        echo "----------------------------------------------";
        echo "To access the auth_backend docs follow the link: http://localhost:8003/docs";
        echo "----------------------------------------------";
        echo "----------------------------------------------";
        echo "To access the deploy_backend docs follow the link: http://localhost:8004/docs";
        echo "----------------------------------------------";

#{
#  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTczMjg4Mjc0Nn0.4B33jxd4YPI3hlExpU_YBWuF1CKI5H8SD8sXQ3LzK8k",
#  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTczMjc5ODE0Nn0.Qu5pzHTR9qoFiyhwIKHhdZXB_dmrfYB5a6MLnl7A4LA"
#}
#
#
