services:

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - "5433:5432"

  auth_backend:
    image: auth-dev
    build:
      context: auth_backend
      target: production
    ports:
      - 8003:8000
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/auth"
      SECRET_KEY: "your-secret-key"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "securepassword"

  frontend:
    image: frontend-dev
    depends_on:
      - auth_backend
    build:
      context: frontend
      target: production
    ports:
      - 8001:80
    environment:
      REACT_APP_AUTH_SERVICE_BASE_URL: http://localhost:8003
      REACT_APP_APPLICATIONS_SERVICE_BASE_URL: http://localhost:8002

  mongodb:
    image: mongo:8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend-pass
    volumes:
      - .mongo:/data/db

  backend:
    image: backend-dev
    depends_on:
      - mongodb
    build:
      context: backend
      target: production
    ports:
      - 8002:8000
    environment:
      MONGO_USER: backend
      MONGO_PASSWORD: backend-pass
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: backend
      MONGO_AUTH_DB_NAME: admin

  mongosh:
    image: rtsp/mongosh
    depends_on:
      - mongodb

  greeting:
    image: alpine
    depends_on:
      - frontend
      - backend
      - mongodb
    command:
      - sh
      - -c
      - |
        sleep 1;
        echo "----------------------------------------------";
        echo "To access the frontend follow the link: http://localhost:8001";
        echo "----------------------------------------------";
        echo "----------------------------------------------";
        echo "To access the backend docs follow the link: http://localhost:8002/docs";
        echo "----------------------------------------------";
        echo "----------------------------------------------";
        echo "To access the auth docs follow the link: http://localhost:8003/docs";
        echo "----------------------------------------------";
