services:

  frontend:
    image: frontend-dev
    build:
      context: frontend
      target: production
    ports:
      - 8001:80
    command:
      - sh
      - -c
      - |
        echo "----------------------------------------------";
        echo "To access the frontend follow the link: http://localhost:8001";
        echo "----------------------------------------------";
        nginx -g 'daemon off;'
