apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
{{ include "certs.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.auth.crt }}
  tls.key: {{ .Values.tls.auth.key }}