apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-configuration
  labels:
{{ include "certs.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.configuration.crt }}
  tls.key: {{ .Values.tls.configuration.key }}