kind: ServiceAccount
apiVersion: v1
metadata:
  name: deploy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: deploy
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: deploy
type: kubernetes.io/service-account-token